### PR TITLE
Add `systemd-setup` command

### PR DESCRIPTION
**Pull request by bendik**

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
This PR assumes 3 things:
1. That there is a binary called `hyperspace` which is not going to be present in most circumstances, since the binary tends to be called `hyp` instead depending on how you installed it. **(Edit: Nevermind. This is a misunderstanding of my own. This ecosystem is a bit too modular and has naming overlaps)**

2. `npm` is on the `PATH` 
3. `systemctl` is on the `PATH`.

These assumptions are too much, this PR reinvents package management, poorly. In a sandboxed scenario, like with Nix, why would the application have access to `npm` or `systemctl`? These are not supposed to be runtime dependencies of any application.

In order to actually install services on Linux systems, you need to comply with the package manager of a given distribution. What this does is bypass that and  will ultimately produce a bad experience.

**Comment by Techjar** [comment]
I agree with @MatthewCroughan, `systemd` services should be handled by the package manager (or the user if they choose to set one up manually). Handling it in the runtime is antithetical to the Linux philosophy, and as stated above this will fall apart when a distribution breaks the built-in assumptions.

**Comment by bendik** [comment]
I agree at runtime isn't the time to install systemd files. This is a separate script that i created before hyp existed.

What it does is integrate hyperdrive better with a linux user. I think its a good thing to offer any user on linux .service files for their daemon-esque processes. Its just not npms job to assume.

I think most linux distributions package managers do offer a .service file for packages that can be installed and 'systemd enabled', eg databases and such. It rarely enables these packages for you but leaves that to the user, leaving it, even when installed, an opt in feature. This pr definitely doesn't force it on anyone.

I do think that a system package manager installing hyp should offer you a systemd integration. With nix things are a little tricky i feel esp with hyperspace's current three service file requirement.

Systemd is only a launcher and integrating with its network.target just makes sense for hyperspace, if you want max uptime and not forcing you to run the cli every time you want these processes started.

Systemd is also not 'PATH'-aware, and users might have odd nvm-ish installations of npm. This seperate systemd-setup script is just being careful about assuming anything about the configuration and system setup before creating a service file. In the users .config directory.

Now, I'll close this and encourage anybody wanting tighter systemd integration with hyperspace to open a pr with something similar as a seperate command in hyp's toolbox.

**Comment by MatthewCroughan** [comment]
> I do think that a system package manager installing hyp should offer you a systemd integration. With nix things are a little tricky i feel esp with hyperspace's current three service file requirement.

All of what you've said is correct, but I don't think it will ever make sense to have `hyp` managing the user's system and modifying files that change the system's behavior. Doing so bypasses the system's state management tools (package manager) and introduces state that is not tracked by anything other than `hyp` into their system, essentially turning `hyp` into a state management utility for Linux systems, which is a bad situation and out-of-scope in my view. Either `hyp` becomes a package manager replacement, or it stays out of it entirely. I do notice that this has only done so in the user's home directory and using a systemd user service, which is much better than most things that modify root, and is perfectly acceptable behavior for most programs, but somehow it just doesn't feel right to do this at all (in my opinion).

The correct way for this to be handled would be for `npm` to support providing systemd user service files as part of an installation, at the very least; rather than `hyp` handling it. This would require changes to `npm` as far as I know.

Nix isn't particularly relevant, I only used it as an example. But it is not difficult to do services there. I will see if I can implement it soon to demonstrate.

**Pull request closed without merging**
